version: '3.8'

services:
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./flask-app/static:/usr/share/nginx/html/static
      - ./flask-app/templates:/usr/share/nginx/html/templates
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - foodtrucks-net

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    container_name: es
    environment:
      - discovery.type=single-node
    networks:
      - foodtrucks-net
    ports:
      - "9200:9200"

  flask-app:
    build:
      context: .
    container_name: flask-app
    depends_on:
      - es
    networks:
      - foodtrucks-net
    environment:
      - DEBUG=true

networks:
  foodtrucks-net:
    driver: bridge
