version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask-app
    networks:
      - foodtrucks-net

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    container_name: es
    environment:
      - discovery.type=single-node
    networks:
      - foodtrucks-net
    ports:
      - "9200:9200"

  flask-app:
    image: foodtrucks-flask-app-light
    container_name: flask-app
    depends_on:
      - es
    networks:
      - foodtrucks-net
    environment:
      - DEBUG=true

networks:
  foodtrucks-net:
    driver: bridge
